version: '3.7'

services:
  server:
    container_name: scheduler
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 6425
    ports:
      - 6425:6425
    restart: 'unless-stopped'
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
